version: '3'

services:
  postgres:
    image: postgres:10
    volumes:
            - postgres_vol:/var/lib/postgresql/data
    environment:
            POSTGRES_PASSWORD: password
    restart: always  

  drupal:
    image: drupal:latest
    ports:
            - 8080:80
    volumes:
            - drupal_modules:/var/www/html/modules
            - drupal_profiles:/var/www/html/profiles
            - drupal_themes:/var/www/html/themes
            - drupal_sites:/var/www/html/sites
    restart: always

volumes:
        drupal_modules:
        drupal_profiles:
        drupal_themes:
        drupal_sites:
        postgres_vol:
